### ISSUE TITLE
Mantab sekali pak

### ISSUE THREAD

**Issue by mnajamudinridha** [basit-adhi/ws_pddikti#1]
saya mau mencoba integrasikan ke sistem akademik kampus saya, tapi kelihatannya banyak sekali yang harus dirubah. untuk singkron aplikasi berarti local pak untuk konek ke feeder? atau sewa vps khusus untuk feedernya? apa tetap bisa sync walaupun siakad dan feedernya beda server? ataukah feeder injectornya diinstall di server feeder? maaf sebelumnya :D

**Comment by basit-adhi** [comment]
On Fri, Apr 20, 2018, 21:46 M. Najamudin Ridha <notifications@github.com>
wrote:

> saya mau mencoba integrasikan ke sistem akademik kampus saya, tapi
> kelihatannya banyak sekali yang harus dirubah.
>
Disesuaikan dengan tabel2 siakad

> untuk singkron aplikasi berarti local pak untuk konek ke feeder? atau sewa
> vps khusus untuk feedernya? apa tetap bisa sync walaupun siakad dan
> feedernya beda server? ataukah feeder injectornya diinstall di server
> feeder? maaf sebelumnya :D
>
Strategi bebas, bisa siakad, feeder dan injectornya jadi satu; bisa semua
dipisah; dan sebagainya tergantung jumlah komputer dan yang penting satu
sama lain bisa saling terkoneksi

**Comment by mnajamudinridha** [comment]
kalau topologinya seperti ini gimana pak
siakad di vps 
injector dipasang di vps
feeder di komputer admin forlapnya (ini dilaptop, tidak diinstall dengan IP public) untuk komunikasi apa bisa singkron data dari laptop ini saja, melalui internet atau dibalik pak

siakad di vps
injector di laptop
feeder di laptop

**Comment by basit-adhi** [comment]
Bebas, pak.. Yang penting bisa saling akses ketiga sistem itu
